### ISSUE TITLE
A more explicit example of the "firestore-one-to-one" extension

### ISSUE THREAD

**Issue by yamankatby** [yamankatby/firebase-extensions#48]
### 🗺️ Roadmap

- [ ] Update the `example` file of the extension params
- [ ] Add it to the README.md
- [ ] Update the explanation video
